apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels: # == tags
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels: # == applies to thing with tag?
      app: nginx
  template:
    metadata:
      labels: # == more tags, tags can be referenced
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

# ---

# apiVersion: v1
# kind: Service
# metadata:
#   name: my-service
# spec:
#   selector:
#     app: nginx
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 9376